### ISSUE TITLE
sdmxHelp enhancement request

### ISSUE THREAD

**Issue by EconGeo** [amattioc/SDMX#20] opened 2014-12-19 05:42 UTC
It would be a lot more useful if there was a way to show remaining dimensions of a DSD available on the sdmxHelp app once one dimension was selected.  For example, if I am looking at the ECB, and a specific dataflow, if I limit it to quarterly FREQ, it would be nice to at least get a a full codelist of remaining dimensions available, but also to know that other dimensions become unavailable when you select quarterly frequency.  As it is now, there's no real way to determine if you have constructed  a valid dataflow code, as each dimension of a DSD is given separately.  It's not a problem on most of the other Euro government websites because their web interface is usable, but the ECB's web interface for searching available codes is so clunky as to be unusable for serious researchers who need multiple series.  BTW, thanks for this package, I've been trying to find some other way of getting code definitions by installing all the SDMX tools provided through sdmx.org and the documentation is not very helpful.

**Comment by amattioc** [comment] 2015-02-09 16:57
@EconGeo 
For 2.1 providers the option *serieskeysonly* can be used to give a preview of the series that are available once some dimensions are selected. E.g.:

http://sdw-wsrest.ecb.europa.eu/service/data/ECB,EXR,1.0/..EUR.SP00.A?detail=serieskeysonly

http://sdw-wsrest.ecb.europa.eu/service/data/EUROSTAT,IEAQ/.I6.N.V.LE.F..A1.S.2.X.E.Z?detail=serieskeysonly

Unfortunately it works only for 2.1 providers.

**Comment by amattioc** [comment] 2015-03-27 19:01
Hi @EconGeo. Please check the latest code level. The helper has changed and now you can check if the query is valid and has contents. I'll close this issue as duplicate of #46 and #54.

I'll be happy to have your feedback...

**Closed** 2015-03-27 19:02 UTC
Labels: enhancement
